CREATE OR REPLACE VIEW sales_master AS
SELECT 
    o.order_id,
    o.order_date,
    DATE_FORMAT(o.order_date, '%Y-%m') AS sales_month,
    c.customer_id,
    c.country,
    p.product_id,
    p.product_name,
    p.category,
    p.price,
    oi.quantity,
    (oi.quantity * p.price) AS line_revenue
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id;

EXPLAIN SELECT 
    c.country, 
    SUM(oi.quantity * p.price) AS total_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY c.country;

WITH customer_cohorts AS (
    -- Step 1: Find the first purchase month for each customer
    SELECT 
        customer_id,
        MIN(DATE_FORMAT(order_date, '%Y-%m-01')) AS cohort_month
    FROM orders
    GROUP BY customer_id
),
cohort_sizes AS (
    -- Step 2: Calculate the total starting size of each cohort
    SELECT 
        cohort_month,
        COUNT(DISTINCT customer_id) AS total_cohort_customers
    FROM customer_cohorts
    GROUP BY cohort_month
),
customer_activity AS (
    -- Step 3: Map all orders to the customer's cohort and calculate month offset
    SELECT 
        o.customer_id,
        cc.cohort_month,
        PERIOD_DIFF(
            DATE_FORMAT(o.order_date, '%Y%m'), 
            DATE_FORMAT(cc.cohort_month, '%Y%m')
        ) AS month_number,
        (oi.quantity * p.price) AS revenue
    FROM orders o
    JOIN customer_cohorts cc ON o.customer_id = cc.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
)
-- Step 4: Aggregate active customers, retention %, and total revenue per period
SELECT 
    ca.cohort_month,
    cs.total_cohort_customers AS cohort_size,
    ca.month_number,
    COUNT(DISTINCT ca.customer_id) AS active_customers,
    ROUND((COUNT(DISTINCT ca.customer_id) / cs.total_cohort_customers) * 100, 2) AS retention_rate_pct,
    ROUND(SUM(ca.revenue), 2) AS total_revenue
FROM customer_activity ca
JOIN cohort_sizes cs ON ca.cohort_month = cs.cohort_month
GROUP BY ca.cohort_month, cs.total_cohort_customers, ca.month_number
ORDER BY ca.cohort_month, ca.month_number;

WITH customer_rfm AS (
    SELECT 
        o.customer_id,
        -- Recency: Days since customer's last order (relative to latest order in database)
        DATEDIFF(
            (SELECT MAX(order_date) FROM orders), 
            MAX(o.order_date)
        ) AS recency_days,
        -- Frequency: Total distinct order count
        COUNT(DISTINCT o.order_id) AS frequency,
        -- Monetary: Total revenue generated by customer
        SUM(oi.quantity * p.price) AS monetary
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY o.customer_id
)
SELECT 
    customer_id,
    recency_days,
    frequency,
    monetary,
    -- R Score: 5 = Most recent (lowest recency_days), 1 = Least recent
    NTILE(5) OVER (
        ORDER BY recency_days DESC
    ) AS r_score,
    -- F Score: 5 = Highest order count, 1 = Lowest order count
    NTILE(5) OVER (
        ORDER BY frequency ASC
    ) AS f_score,
    -- M Score: 5 = Highest total spend, 1 = Lowest total spend
    NTILE(5) OVER (
        ORDER BY monetary ASC
    ) AS m_score
FROM customer_rfm
ORDER BY monetary DESC;

DELETE oi1 
FROM order_items oi1
INNER JOIN order_items oi2 
    ON oi1.order_id = oi2.order_id 
   AND oi1.product_id = oi2.product_id 
   AND oi1.order_item_id > oi2.order_item_id;
   
WITH first_purchases AS (
    -- CTE 1: Identify acquisition (first purchase) month per customer
    SELECT 
        o.customer_id,
        MIN(DATE_FORMAT(o.order_date, '%Y-%m-01')) AS cohort_month
    FROM orders o
    GROUP BY 
        o.customer_id
),

cohort_sizes AS (
    -- CTE 2: Calculate baseline customer volume for each cohort
    SELECT 
        fp.cohort_month,
        COUNT(DISTINCT fp.customer_id) AS cohort_size
    FROM first_purchases fp
    GROUP BY 
        fp.cohort_month
),

order_line_revenue AS (
    -- CTE 3: Calculate calculated line-item sales revenue
    SELECT 
        o.order_id,
        o.customer_id,
        o.order_date,
        (oi.quantity * p.price) AS line_revenue
    FROM orders o
    INNER JOIN order_items oi 
        ON o.order_id = oi.order_id
    INNER JOIN products p 
        ON oi.product_id = p.product_id
),

customer_cohort_activity AS (
    -- CTE 4: Map purchase events to cohort acquisition month and index offset
    SELECT 
        olr.customer_id,
        fp.cohort_month,
        PERIOD_DIFF(
            DATE_FORMAT(olr.order_date, '%Y%m'),
            DATE_FORMAT(fp.cohort_month, '%Y%m')
        ) AS month_number,
        olr.line_revenue
    FROM order_line_revenue olr
    INNER JOIN first_purchases fp 
        ON olr.customer_id = fp.customer_id
),

cohort_metrics AS (
    -- CTE 5: Aggregate unique active users and revenue per cohort & period
    SELECT 
        cca.cohort_month,
        cca.month_number,
        COUNT(DISTINCT cca.customer_id) AS active_customers,
        SUM(cca.line_revenue) AS monthly_revenue
    FROM customer_cohort_activity cca
    GROUP BY 
        cca.cohort_month,
        cca.month_number
)

-- Final Output: Calculate retention rates and ARPU (Average Revenue Per User)
SELECT 
    cm.cohort_month,
    cs.cohort_size,
    cm.month_number AS cohort_index_month,
    cm.active_customers,
    ROUND((cm.active_customers / cs.cohort_size) * 100, 2) AS retention_rate_pct,
    ROUND(cm.monthly_revenue, 2) AS total_revenue,
    ROUND(cm.monthly_revenue / cs.cohort_size, 2) AS avg_revenue_per_cohort_user
FROM cohort_metrics cm
INNER JOIN cohort_sizes cs 
    ON cm.cohort_month = cs.cohort_month
ORDER BY 
    cm.cohort_month ASC,
    cm.month_number ASC;
   
